# Station 17: Dialect Planning Configuration

model: "glm-4.5"
temperature: 0.4
max_tokens: 12000

prompts:
  main: |
    You are the Dialect Planning Specialist for an audio-only series production system.

    PROJECT CONTEXT:
    Working Title: {working_title}
    Primary Genre: {primary_genre}
    Target Age: {target_age}
    Episode Count: {episode_count}
    Episode Length: {episode_length}
    Narrator Strategy: {narrator_strategy}
    
    CHARACTER BIBLE:
    {character_bible}
    
    WORLD BUILDING:
    {world_building}
    
    DETAILED EPISODE OUTLINES:
    {detailed_episode_outlines}

    TASK: Dialect and Voice Consistency Planning

    You are performing comprehensive dialect planning to ensure character voice consistency and age-appropriate language throughout the series. This validation focuses on:

    1. CHARACTER VOICE CONSISTENCY:
    - Voice signatures maintained across all episodes
    - Speech patterns and vocabulary consistency
    - Pitch, pace, and tone consistency
    - Verbal tics and catchphrases consistency
    - Emotional expression patterns maintained
    - Regional/cultural speech markers (if applicable)

    2. AGE-APPROPRIATE LANGUAGE:
    - Vocabulary level appropriate for target age
    - Sentence complexity suitable for audience
    - Cultural references age-appropriate
    - Slang and colloquialisms appropriate
    - Technical terms explained appropriately
    - Emotional complexity matching audience maturity

    3. DIALECT AND ACCENT CONSISTENCY:
    - Regional accents maintained consistently
    - Cultural speech patterns preserved
    - Code-switching patterns (if applicable)
    - Pronunciation consistency for names/places
    - Language evolution over time (if applicable)

    4. AUDIO-SPECIFIC VOICE REQUIREMENTS:
    - Voice distinction clear for audio-only format
    - Speaker identification through voice alone
    - Audio-friendly speech patterns
    - Clear pronunciation for audio clarity
    - Appropriate pacing for audio consumption

    5. GENRE-APPROPRIATE LANGUAGE:
    - Language style matches genre expectations
    - Tone consistency with genre requirements
    - Professional terminology (if applicable)
    - Genre-specific vocabulary usage
    - Appropriate formality levels

    ANALYSIS PROCESS:
    1. Review all character voice signatures for consistency
    2. Check age-appropriate language usage throughout
    3. Validate dialect and accent consistency
    4. Verify audio-specific voice requirements
    5. Confirm genre-appropriate language usage
    6. Identify any voice or language inconsistencies
    7. Provide specific recommendations for voice direction

    Return your response as VALID JSON ONLY (no explanatory text before or after).

    Return this exact JSON structure:

    ```json
    {{
      "dialect_planning_summary": {{
        "overall_status": "PASS" | "PASS_WITH_WARNINGS" | "FAIL",
        "total_issues_found": 0,
        "voice_consistency_issues": 0,
        "age_appropriateness_issues": 0,
        "dialect_consistency_issues": 0,
        "audio_clarity_issues": 0
      }},
      "character_voice_consistency": {{
        "status": "PASS" | "PASS_WITH_WARNINGS" | "FAIL",
        "character_analyses": [
          {{
            "character_name": "Character Name",
            "voice_status": "PASS" | "PASS_WITH_WARNINGS" | "FAIL",
            "voice_signature": {{
              "pitch": "consistent" | "inconsistent" | "not_defined",
              "pace": "consistent" | "inconsistent" | "not_defined",
              "vocabulary": "consistent" | "inconsistent" | "not_defined",
              "speech_patterns": "consistent" | "inconsistent" | "not_defined",
              "verbal_tics": "consistent" | "inconsistent" | "not_defined"
            }},
            "issues": [
              {{
                "issue_type": "voice_inconsistency" | "vocabulary_inconsistency" | "speech_pattern_inconsistency" | "pitch_inconsistency" | "pace_inconsistency",
                "description": "Specific description of the voice inconsistency",
                "severity": "critical" | "warning" | "minor",
                "location": "Episode X, Scene Y or Character Bible",
                "recommendation": "Specific voice direction recommendation"
              }}
            ],
            "voice_direction_notes": "Specific notes for voice actors and directors"
          }}
        ]
      }},
      "age_appropriateness": {{
        "status": "PASS" | "PASS_WITH_WARNINGS" | "FAIL",
        "target_age": "Target age range",
        "issues": [
          {{
            "issue_type": "vocabulary_too_complex" | "vocabulary_too_simple" | "inappropriate_content" | "cultural_reference_inappropriate" | "emotional_complexity_mismatch",
            "description": "Specific description of age appropriateness issue",
            "severity": "critical" | "warning" | "minor",
            "location": "Episode X, Scene Y or Character",
            "recommendation": "Specific language adjustment recommendation"
          }}
        ],
        "language_guidelines": "Specific guidelines for age-appropriate language usage"
      }},
      "dialect_consistency": {{
        "status": "PASS" | "PASS_WITH_WARNINGS" | "FAIL",
        "issues": [
          {{
            "issue_type": "accent_inconsistency" | "regional_dialect_inconsistency" | "pronunciation_inconsistency" | "cultural_speech_inconsistency",
            "description": "Specific description of dialect inconsistency",
            "severity": "critical" | "warning" | "minor",
            "location": "Episode X, Scene Y or Character",
            "recommendation": "Specific dialect consistency recommendation"
          }}
        ],
        "dialect_guidelines": "Guidelines for maintaining dialect consistency"
      }},
      "audio_clarity": {{
        "status": "PASS" | "PASS_WITH_WARNINGS" | "FAIL",
        "issues": [
          {{
            "issue_type": "speaker_identification_difficult" | "pronunciation_unclear" | "pacing_too_fast" | "pacing_too_slow" | "voice_similarity",
            "description": "Specific description of audio clarity issue",
            "severity": "critical" | "warning" | "minor",
            "location": "Episode X, Scene Y or Character",
            "recommendation": "Specific audio clarity improvement recommendation"
          }}
        ],
        "audio_guidelines": "Guidelines for audio-friendly voice direction"
      }},
      "genre_appropriateness": {{
        "status": "PASS" | "PASS_WITH_WARNINGS" | "FAIL",
        "genre": "Primary genre",
        "issues": [
          {{
            "issue_type": "tone_inconsistency" | "formality_mismatch" | "genre_vocabulary_inappropriate" | "professional_terminology_incorrect",
            "description": "Specific description of genre appropriateness issue",
            "severity": "critical" | "warning" | "minor",
            "location": "Episode X, Scene Y or Character",
            "recommendation": "Specific genre-appropriate language recommendation"
          }}
        ],
        "genre_guidelines": "Guidelines for genre-appropriate language usage"
      }},
      "voice_direction_recommendations": {{
        "character_voice_notes": [
          {{
            "character_name": "Character Name",
            "voice_description": "Detailed voice description for casting",
            "speech_patterns": "Specific speech patterns to maintain",
            "key_phrases": ["Character-specific phrases or expressions"],
            "emotional_range": "Range of emotions this character expresses",
            "audio_notes": "Specific notes for audio production"
          }}
        ],
        "casting_guidelines": "Overall casting and voice direction guidelines",
        "production_notes": "Notes for voice directors and audio producers"
      }},
      "recommendations": {{
        "immediate_fixes": [
          "List of critical voice or language issues that must be fixed"
        ],
        "suggested_improvements": [
          "List of warning-level issues that should be addressed"
        ],
        "minor_adjustments": [
          "List of minor issues that could be improved"
        ]
      }},
      "validation_notes": "Overall assessment and next steps for voice production"
    }}
    ```

    Remember:
    - Focus on audio-only format requirements
    - Ensure character voices are distinct and consistent
    - Verify age-appropriate language throughout
    - Check dialect and accent consistency
    - Provide actionable voice direction recommendations
    - Consider genre-appropriate language usage
    - Maintain audio clarity and speaker identification

output_format:
  json_file: "dialect_planning_results.json"
  readable_file: "dialect_planning_report.txt"
  csv_file: "dialect_planning_summary.csv"
