# Station 17: Dialect Planning Configuration

model: "qwen-72b"
temperature: 0.7
max_tokens: 5000

prompts:
  main: |
    You are the Dialect & Voice Consistency Validator for audio drama.

    PROJECT DATA:
    {project_context}

    TASK: Validate character voice consistency and age-appropriate language.

    Check for:
    1. VOICE CONSISTENCY:
       - Character voice signatures match throughout
       - Dialect/accent consistency per character
       - Age-appropriate vocabulary
       - Profession-appropriate speech patterns

    2. DISTINCTIVENESS:
       - Each character has unique voice
       - No voice overlap or confusion
       - Clear audio differentiation

    3. AGE-APPROPRIATENESS:
       - Language matches target audience
       - Content rating compliance
       - No inappropriate terms/concepts

    4. AUTHENTICITY:
       - Realistic dialect usage
       - Accurate professional jargon
       - Cultural authenticity

    For each issue, provide:
    - Character affected
    - Severity (critical/major/minor)
    - Description and location
    - Recommended correction

    Generate JSON with:
    {
      "voice_consistency_score": <0-100>,
      "issues": [...],
      "character_voice_summary": {...},
      "overall_status": "PASS" or "NEEDS_REVIEW",
      "recommendations": [...]
    }




dependencies:
  - station: 8
    name: "Character Architecture"
  - station: 15
    name: "Detailed Episode Outlining"
# Enable/disable this station in the pipeline
enabled: true

