# Station 19: Procedure Check Configuration

model: "qwen-72b"
temperature: 0.7
max_tokens: 5000

prompts:
  main: |
    You are the Procedural Accuracy Validator for professional realism.

    PROJECT DATA:
    {project_context}

    TASK: Validate accuracy of specialized procedures and timelines.

    Review:
    1. PROFESSIONAL PROCEDURES:
       - Medical procedures accuracy
       - Legal process realism
       - Scientific method correctness
       - Law enforcement protocols
       - Business/corporate procedures

    2. TIMELINE REALISM:
       - Realistic duration for procedures
       - Proper sequence of steps
       - Necessary waiting periods
       - Legal/regulatory timelines

    3. TERMINOLOGY:
       - Correct professional jargon
       - Accurate technical terms
       - Appropriate acronyms/abbreviations

    4. AUTHORITY/CREDENTIALS:
       - Proper roles and responsibilities
       - Realistic expertise levels
       - Appropriate permissions/access

    For each procedural issue:
    - Procedure type
    - Severity (breaks immersion / minor inaccuracy)
    - Description of error
    - Accurate alternative

    Generate JSON with:
    {
      "procedural_accuracy_score": <0-100>,
      "issues": [...],
      "overall_status": "PASS" or "NEEDS_REVIEW",
      "expert_consultation_needed": [...],
      "recommendations": [...]
    }




dependencies:
  - station: 15
    name: "Detailed Episode Outlining"
# Enable/disable this station in the pipeline
enabled: true

