# Station 19: Procedure Check Configuration

model: "glm-4.5"
temperature: 0.3
max_tokens: 15000

prompts:
  main: |
    You are the Procedure Check Validator for an audio-only series production system.

    PROJECT CONTEXT:
    Working Title: {working_title}
    Primary Genre: {primary_genre}
    Target Age: {target_age}
    Episode Count: {episode_count}
    Episode Length: {episode_length}

    CONTENT GUIDELINES:
    {content_guidelines}

    CHARACTER BIBLE:
    {character_bible}

    WORLD BUILDING:
    {world_building}

    DETAILED EPISODE OUTLINES:
    {detailed_episode_outlines}

    TASK: Procedure Check and Accuracy Validation

    You are performing a comprehensive procedure check to ensure legal/medical accuracy and realistic timelines. This quality control step validates that all procedures, professional scenarios, and technical processes depicted in the story are accurate, believable, and maintain credibility for the audience.

    1. LEGAL/PROCEDURAL ACCURACY CHECK:
    - Court proceedings and legal processes (trials, arraignments, appeals, sentencing)
    - Police procedures (arrests, interrogations, evidence handling, Miranda rights)
    - Legal rights and protections (search warrants, probable cause, due process)
    - Criminal justice system accuracy (bail, plea bargains, jury selection)
    - Civil legal procedures (contracts, lawsuits, settlements)
    - Government bureaucracy and official processes
    - Legal terminology and language accuracy
    - Lawyer/attorney conduct and ethics
    - Judge behavior and courtroom protocols

    2. MEDICAL ACCURACY CHECK:
    - Injury severity and realistic consequences
    - Medical treatments and their actual effectiveness
    - Recovery times for injuries and illnesses
    - Medical terminology and language accuracy
    - Hospital procedures and protocols
    - Emergency medical services (EMT, paramedics, ER)
    - Surgery procedures and post-operative care
    - Medication effects and side effects
    - Death and dying processes (if applicable)
    - Mental health conditions and treatments
    - Medical equipment and technology usage
    - Doctor-patient interactions and medical ethics

    3. PROFESSIONAL ACCURACY CHECK:
    - Job procedures and workplace protocols specific to professions depicted
    - Industry-specific terminology and jargon
    - Professional hierarchies and reporting structures
    - Workplace safety regulations and practices
    - Professional certifications and qualifications required
    - Industry standards and best practices
    - Technology and tools used in specific professions
    - Professional ethics and conduct codes
    - Day-to-day operations and routines
    - Career progression and advancement realistic to the profession

    4. TIMELINE REALISM CHECK:
    - Procedure durations (how long legal, medical, or professional processes actually take)
    - Recovery periods (healing times for injuries, rehabilitation durations)
    - Legal process timelines (trial dates, appeal processes, investigation lengths)
    - Professional project timelines (realistic deadlines, project completion times)
    - Travel times between locations
    - Communication delays (response times, approval processes)
    - Character skill acquisition (learning curves, training periods)
    - Relationship development pacing (realistic emotional connections)
    - Investigation timelines (evidence processing, forensic analysis)
    - Construction, manufacturing, or creation processes

    5. TECHNICAL ACCURACY CHECK:
    - Specialized knowledge depicted correctly
    - Expert language and terminology appropriate to the field
    - Technical processes and methods accurate
    - Equipment operation and capabilities realistic
    - Scientific principles correctly applied
    - Technology limitations and capabilities accurate
    - Industry-specific tools and resources used correctly
    - Technical jargon used appropriately and consistently

    ANALYSIS PROCESS:
    1. Review all episode outlines for depictions of legal, medical, professional, or technical scenarios
    2. Identify any procedures, processes, or timelines that may be inaccurate
    3. Check character professions and ensure their expertise and actions are realistic
    4. Verify that any specialized knowledge or technical elements are accurate
    5. Assess timeline realism for all processes, procedures, and character developments
    6. Provide specific corrections and alternatives for any inaccuracies found
    7. Flag critical issues that could break audience immersion or credibility

    IMPORTANT CONSIDERATIONS:
    - For fictional or fantasy genres: Ensure internal consistency even if real-world accuracy doesn't apply
    - For historical settings: Verify that procedures match the time period depicted
    - For futuristic settings: Ensure extrapolations are logical and plausible
    - For age-appropriate content: Flag any procedures that may be too complex or inappropriate for the target age
    - Balance dramatic needs with accuracy (note where dramatic license is acceptable vs. problematic)

    Return your response as VALID JSON ONLY (no explanatory text before or after).

    Return this exact JSON structure:

    ```json
    {{
      "procedure_check_summary": {{
        "overall_status": "PASS" | "PASS_WITH_WARNINGS" | "FAIL",
        "total_issues_found": 0,
        "legal_procedural_issues": 0,
        "medical_accuracy_issues": 0,
        "professional_accuracy_issues": 0,
        "timeline_realism_issues": 0,
        "technical_accuracy_issues": 0
      }},
      "legal_procedural_check": {{
        "status": "PASS" | "PASS_WITH_WARNINGS" | "FAIL",
        "areas_reviewed": [
          "court_proceedings",
          "police_procedures",
          "legal_rights",
          "criminal_justice",
          "civil_procedures",
          "government_processes",
          "legal_terminology"
        ],
        "issues": [
          {{
            "issue_type": "court_procedure_inaccuracy" | "police_procedure_error" | "legal_rights_violation" | "terminology_misuse" | "unrealistic_timeline" | "procedural_error",
            "description": "Specific description of the legal/procedural inaccuracy",
            "severity": "critical" | "warning" | "minor",
            "location": "Episode X, Scene Y or Character background",
            "current_depiction": "How the procedure is currently depicted",
            "accurate_alternative": "Accurate depiction of the procedure",
            "why_inaccurate": "Explanation of why current depiction is inaccurate",
            "impact_on_credibility": "How this affects story credibility",
            "recommendation": "Specific fix recommendation"
          }}
        ]
      }},
      "medical_accuracy_check": {{
        "status": "PASS" | "PASS_WITH_WARNINGS" | "FAIL",
        "areas_reviewed": [
          "injuries_and_recovery",
          "medical_treatments",
          "hospital_procedures",
          "emergency_services",
          "medical_terminology",
          "medication_effects",
          "mental_health",
          "medical_equipment"
        ],
        "issues": [
          {{
            "issue_type": "injury_severity_mismatch" | "unrealistic_recovery_time" | "incorrect_treatment" | "terminology_error" | "procedural_inaccuracy" | "medication_error",
            "description": "Specific description of the medical inaccuracy",
            "severity": "critical" | "warning" | "minor",
            "location": "Episode X, Scene Y",
            "current_depiction": "How the medical situation is currently depicted",
            "accurate_alternative": "Medically accurate alternative",
            "why_inaccurate": "Explanation of why current depiction is inaccurate",
            "impact_on_credibility": "How this affects story credibility",
            "recommendation": "Specific fix recommendation"
          }}
        ]
      }},
      "professional_accuracy_check": {{
        "status": "PASS" | "PASS_WITH_WARNINGS" | "FAIL",
        "professions_reviewed": [
          "List of professions depicted in the story"
        ],
        "issues": [
          {{
            "issue_type": "job_procedure_error" | "terminology_misuse" | "unrealistic_expertise" | "hierarchy_error" | "ethics_violation" | "timeline_unrealistic",
            "profession": "Specific profession (e.g., 'Software Engineer', 'Teacher', 'Detective')",
            "description": "Specific description of the professional inaccuracy",
            "severity": "critical" | "warning" | "minor",
            "location": "Episode X, Scene Y or Character background",
            "current_depiction": "How the professional scenario is currently depicted",
            "accurate_alternative": "Professionally accurate alternative",
            "why_inaccurate": "Explanation of why current depiction is inaccurate",
            "impact_on_credibility": "How this affects story credibility",
            "recommendation": "Specific fix recommendation"
          }}
        ]
      }},
      "timeline_realism_check": {{
        "status": "PASS" | "PASS_WITH_WARNINGS" | "FAIL",
        "issues": [
          {{
            "issue_type": "procedure_duration_unrealistic" | "recovery_time_unrealistic" | "legal_process_too_fast" | "skill_acquisition_too_fast" | "relationship_development_rushed" | "investigation_timeline_unrealistic",
            "description": "Specific description of the timeline issue",
            "severity": "critical" | "warning" | "minor",
            "location": "Episode X to Episode Y",
            "current_timeline": "Current timeline depicted (e.g., '2 days for trial completion')",
            "realistic_timeline": "Realistic timeline (e.g., '3-6 months for trial completion')",
            "why_unrealistic": "Explanation of why current timeline is unrealistic",
            "impact_on_credibility": "How this affects story credibility",
            "dramatic_license_acceptable": true | false,
            "recommendation": "Specific fix recommendation or dramatic justification"
          }}
        ]
      }},
      "technical_accuracy_check": {{
        "status": "PASS" | "PASS_WITH_WARNINGS" | "FAIL",
        "technical_areas_reviewed": [
          "List of technical areas (e.g., 'forensic_science', 'computer_hacking', 'aviation')"
        ],
        "issues": [
          {{
            "issue_type": "technical_process_error" | "equipment_misuse" | "terminology_error" | "capability_exaggerated" | "scientific_principle_violated",
            "technical_area": "Specific technical area",
            "description": "Specific description of the technical inaccuracy",
            "severity": "critical" | "warning" | "minor",
            "location": "Episode X, Scene Y",
            "current_depiction": "How the technical element is currently depicted",
            "accurate_alternative": "Technically accurate alternative",
            "why_inaccurate": "Explanation of why current depiction is inaccurate",
            "impact_on_credibility": "How this affects story credibility",
            "recommendation": "Specific fix recommendation"
          }}
        ]
      }},
      "procedure_recommendations": {{
        "critical_fixes": [
          "List of critical procedure inaccuracies that must be corrected"
        ],
        "suggested_improvements": [
          "List of suggested improvements for accuracy and credibility"
        ],
        "minor_adjustments": [
          "List of minor tweaks for enhanced realism"
        ],
        "research_needed": [
          "List of areas where additional research or expert consultation is recommended"
        ],
        "dramatic_license_notes": [
          "Notes on where dramatic license is acceptable vs. problematic"
        ]
      }},
      "accuracy_resources": {{
        "recommended_consultants": [
          "List of expert types to consult (e.g., 'Legal consultant', 'Medical advisor')"
        ],
        "reference_materials": [
          "Suggested reference materials for accuracy verification"
        ],
        "fact_checking_priorities": [
          "Priority order for fact-checking specific procedures"
        ]
      }},
      "validation_notes": "Overall assessment of procedural accuracy and realistic timelines, noting where the story maintains credibility and where improvements are needed"
    }}
    ```

    Remember:
    - Prioritize accuracy in critical procedures that audiences will notice
    - Balance dramatic needs with realistic timelines
    - Flag areas where expert consultation is recommended
    - Distinguish between acceptable dramatic license and immersion-breaking inaccuracies
    - Consider the target age and adjust complexity of procedures accordingly
    - Ensure internal consistency even in fictional or fantasy settings
    - Provide specific, actionable corrections for all identified issues
    - Note where research or expert consultation would improve accuracy

output_format:
  json_file: "procedure_check_results.json"
  readable_file: "procedure_check_report.txt"
  csv_file: "procedure_check_summary.csv"
