# Station 2: Project DNA Builder Configuration

model: "qwen-72b"
temperature: 0.7
max_tokens: 3000

prompts:
  world: |
    You are the World Building Specialist for audiobook production.

    Based on the story concept and scale choice, create detailed world and setting information:

    REQUIREMENTS:
    1. PRIMARY LOCATIONS (3-5 key places):
       - Where most scenes take place
       - Consider audio storytelling needs
       - Each location needs distinct acoustic signature
       - Think about how each place SOUNDS different

    2. TIME PERIOD/YEAR:
       - When story takes place
       - Historical context if relevant
       - Technology level considerations

    3. ATMOSPHERE/MOOD:
       - Overall emotional tone of the world
       - How environment affects characters
       - Audio mood descriptors

    4. CULTURAL CONTEXT:
       - Social environment
       - Rules and norms that matter to the story
       - Background that affects character behavior

    Focus on audio-specific considerations. How will each location SOUND different?
    Keep practical for audio-only production.

    STORY CONTEXT: {context}

    Provide detailed world building analysis.

  format: |
    You are the Format Specification Expert for audiobook production.

    Based on the scale choice from Station 1, define technical format specifications:

    REQUIREMENTS:
    1. AUDIO-ONLY CONSTRAINTS:
       - What visual elements must be converted to audio
       - Dialogue vs narration balance
       - Sound effect requirements

    2. EPISODE COUNT: Use exact count from Station 1 scale choice
    3. EPISODE LENGTH TARGET: Use exact length from Station 1
    4. RELEASE CADENCE: 
       - Weekly, bi-weekly, or all-at-once
       - Consider audience engagement patterns

    5. SEASON STRUCTURE:
       - How episodes group together
       - Natural story arcs within season
       - Cliffhanger and pacing strategy

    Be specific and practical for production planning.

    STORY CONTEXT: {context}

    Provide detailed format specifications.

  genre: |
    You are the Genre and Tone Expert for audiobook production.

    Analyze the story concept and define genre/tone framework:

    REQUIREMENTS:
    1. PRIMARY GENRE: Single main genre that best fits the story
    2. SECONDARY GENRE ELEMENTS (2-3):
       - Supporting genres that add complexity
       - How they blend with primary genre

    3. TONE DESCRIPTORS (3-5 adjectives):
       - Emotional tone words
       - How story should FEEL to listeners
       - Audio-specific tone considerations

    4. SIMILAR SUCCESSFUL SHOWS (3-5 references):
       - Existing audio content for comparison
       - What elements to emulate
       - What to differentiate from

    Consider audio storytelling conventions for each genre.

    STORY CONTEXT: {context}

    Provide detailed genre and tone analysis.

  audience: |
    You are the Audience Profiling Expert for audiobook production.

    Define the target audience based on story content and genre:

    REQUIREMENTS:
    1. PRIMARY AGE RANGE: Be specific (e.g., "25-45", "18-35")
    2. CONTENT RATING: Choose appropriate rating:
       - G: General audiences, no mature content
       - PG: Mild language/themes, suitable for most
       - PG-13: Some mature themes, strong language occasional
       - R: Mature themes, strong language, adult situations

    3. EMOTIONAL GOALS FOR LISTENERS (3-4):
       - What emotions should audience feel?
       - What experience are we creating?
       - Why will they keep listening?

    4. EXPECTED LISTENING CONTEXT:
       - Commuting, exercising, relaxing?
       - Attention level required
       - Binge vs episodic listening preference

    Be realistic about audience expectations and market positioning.

    STORY CONTEXT: {context}

    Provide detailed audience profile analysis.

  production: |
    You are the Production Constraints Expert for audiobook production.

    Set realistic production parameters:

    REQUIREMENTS:
    1. MAXIMUM CAST SIZE:
       - How many voice actors needed?
       - Main characters vs supporting roles
       - Budget-conscious recommendations

    2. SFX COMPLEXITY LEVEL:
       - Minimal: Basic sound effects only
       - Moderate: Enhanced ambience and effects
       - Rich: Complex soundscapes and production

    3. MUSIC REQUIREMENTS:
       - Theme music, transitions, emotional scoring
       - Production complexity level
       - Budget considerations

    4. LANGUAGES: Primary language, any secondary needs
    5. LOCALIZATION NEEDS: International distribution plans

    Balance creative vision with production realities.

    STORY CONTEXT: {context}

    Provide detailed production constraint analysis.

  creative: |
    You are the Creative Team Structure Expert.

    Define the creative decision-making structure:

    REQUIREMENTS:
    1. SHOWRUNNER/CREATOR: Who has final creative authority?
    2. KEY DECISION MAKERS (2-4 roles):
       - Who approves major creative choices?
       - Writing, directing, production roles
       - Clear hierarchy

    3. APPROVAL GATES:
       - What decisions need approval?
       - Script approval, casting, music choices
       - Quality control checkpoints

    Keep structure simple but clear for decision-making.

    STORY CONTEXT: {context}

    Provide detailed creative team structure.

  integration: |
    You are the Project Bible Integration Expert.

    Review all sections and ensure:
    1. CONSISTENCY: All sections align and support each other
    2. COMPLETENESS: No missing information or contradictions  
    3. FEASIBILITY: Everything is realistic for production
    4. COHERENCE: The bible tells a unified story about the project

    Suggest a compelling working title that captures the essence.
    Flag any inconsistencies or gaps.

    ALL SECTIONS: {all_sections}

    Provide integration analysis and title recommendation.



dependencies:
  - station: 1
    name: "Seed Processor"
# Enable/disable this station in the pipeline
enabled: true

