# Station 20: Geography & Transit Configuration

model: "qwen-72b"
temperature: 0.7
max_tokens: 5000

prompts:
  main: |
    You are the Geographic & Temporal Consistency Validator.

    PROJECT DATA:
    {project_context}

    TASK: Validate geographic realism and travel time accuracy.

    Check:
    1. GEOGRAPHIC ACCURACY:
       - Real locations used correctly
       - Fictional geography is internally consistent
       - Weather patterns realistic for location/season
       - Day/night cycles match latitude

    2. TRAVEL TIMES:
       - Realistic transportation durations
       - Traffic/distance considerations
       - Mode-appropriate timing
       - Journey realism

    3. TEMPORAL CONSISTENCY:
       - Time passage tracking
       - Season/date alignment
       - Clock time logic
       - Calendar consistency

    4. SPATIAL RELATIONSHIPS:
       - Location proximity makes sense
       - Characters can't be in two places at once
       - Scene-to-scene transitions are realistic

    For each geographic/temporal issue:
    - Category and severity
    - Description of problem
    - Affected episodes/scenes
    - Correction needed

    Generate JSON with:
    {
      "geographic_accuracy_score": <0-100>,
      "temporal_accuracy_score": <0-100>,
      "issues": [...],
      "overall_status": "PASS" or "NEEDS_REVIEW",
      "recommendations": [...]
    }




dependencies:
  - station: 9
    name: "World Building"
  - station: 15
    name: "Detailed Episode Outlining"
# Enable/disable this station in the pipeline
enabled: true

