# Station 4: Reference Mining & Seed Extraction Configuration

model: "z-ai/glm-4.5"
temperature: 0.7
max_tokens: 16000

prompts:
  reference_gathering: |
    You are the Reference Curator for audio drama development.

    PROJECT CONTEXT:
    Title: {working_title}
    Primary Genre: {primary_genre}
    Secondary Genres: {secondary_genres}
    Target Age Range: {target_age_range}
    Content Rating: {content_rating}

    Identify 20-25 cross-media references. Return ONLY valid JSON:

    ```json
    {{
      "references": [
        {{
          "title": "Exact title",
          "medium": "Audio Drama or Film or TV or Literature or Podcast or Interactive",
          "release_year": "2020",
          "creator": "Creator name",
          "genre_relevance": "How it matches our genre",
          "age_appropriateness": "Why it fits our rating",
          "why_selected": "2-3 sentences on storytelling value"
        }}
      ]
    }}
    ```

    CRITICAL: Return array of 20-25 references as valid JSON only.

  tactical_extraction: |
    Extract storytelling tactics from this reference for audio drama.

    PROJECT: {project_context}
    REFERENCE: {reference_details}

    Return ONLY valid JSON:

    ```json
    {{
      "storytelling_tactic": "Technique name and description",
      "pitfall_to_avoid": "What to avoid and why",
      "audio_technique": "Audio-specific technique",
      "applicability_score": 0.85,
      "implementation_notes": "How to apply this"
    }}
    ```

    CRITICAL: Return valid JSON only.

  seed_generation: |
    Generate 65 story seeds for audio drama production.

    PROJECT: {project_context}
    TACTICS: {available_tactics}
    CHARACTERS: {main_characters}

    IMPORTANT: Use ONLY the actual character names provided in CHARACTERS. Do not invent new character names.

    Return ONLY valid JSON with exactly 30+20+10+5 seeds:

    ```json
    {{
      "micro_moments": [
        {{
          "title": "Seed title",
          "description": "2-3 sentences",
          "audio_considerations": "Audio-specific notes",
          "difficulty": "Easy or Medium or Hard",
          "characters": ["Character 1", "Character 2"],
          "setting": "Setting description",
          "runtime": "30-90 seconds",
          "tags": ["Genre tag 1", "Genre tag 2"],
          "source_reference": "Reference title",
          "adaptation_notes": "How to adapt for audio"
        }}
      ],
      "episode_beats": [ /* 20 seeds with same structure */ ],
      "season_arcs": [ /* 10 seeds with same structure */ ],
      "series_defining": [ /* 5 seeds with same structure */ ]
    }}
    ```

    CRITICAL: Generate exactly 30 micro_moments, 20 episode_beats, 10 season_arcs, 5 series_defining. JSON only.



dependencies:
  - station: 1
    name: "Seed Processor"
  - station: 2
    name: "Project DNA Builder"
  - station: 3
    name: "Age Genre Optimizer"
# Enable/disable this station in the pipeline
enabled: true

