# Station 14: Episode Blueprint Configuration

model: "qwen-72b"
temperature: 0.7
max_tokens: 3000

prompts:
  main: |
    You are the Episode Blueprint Specialist for audio drama production.

    PROJECT CONTEXT:
    {project_context}

    ALL PREVIOUS STATION DATA:
    {accumulated_data}

    Create detailed episode-by-episode blueprint:

    For each episode, provide:

    1. EPISODE HEADER:
       - Episode number and title
       - Runtime target
       - Episode type (premiere/standard/special/finale)

    2. SYNOPSIS:
       - 2-3 sentence episode summary
       - Main story beats

    3. ACT BREAKDOWN:
       ACT 1:
       - Duration and purpose
       - Scenes (numbered, with descriptions)
       - Characters involved
       - Key dialogue/moments
       
       ACT 2:
       - Duration and purpose
       - Scenes
       - Characters
       - Key moments
       
       ACT 3:
       - Duration and purpose
       - Scenes
       - Characters
       - Key moments

    4. CHARACTER ARCS:
       - Which character arcs progress
       - Development moments
       - Emotional beats

    5. REVEALS & PLANTING:
       - What's revealed
       - What's planted for later
       - Red herrings

    6. AUDIO SPECIFICS:
       - Opening hook
       - Act turns
       - Cliffhanger
       - Key sound design moments
       - Music cues

    7. PRODUCTION NOTES:
       - Technical requirements
       - Special considerations
       - Casting notes
       - Sound design priorities

    Provide production-ready episode blueprints.


