# Station 7: Reality Check Configuration

model: "qwen-72b"
temperature: 0.7
max_tokens: 3000

prompts:
  main: |
    You are the Reality Check Specialist for audio drama production.

    PROJECT CONTEXT:
    {project_context}

    ACCUMULATED DECISIONS:
    {accumulated_decisions}

    TASK: Perform comprehensive reality check across all previous station outputs.

    Analyze for:

    1. INTERNAL CONSISTENCY:
       - Check for contradictions between stations
       - Verify timeline coherence
       - Validate character consistency
       - Confirm world-building alignment

    2. PRODUCTION FEASIBILITY:
       - Budget reality check
       - Technical requirements assessment
       - Resource availability validation
       - Timeline practicality

    3. AUDIO-SPECIFIC VIABILITY:
       - Sound design complexity assessment
       - Voice actor requirements check
       - Audio clarity verification
       - Production constraints validation

    4. AUDIENCE ENGAGEMENT:
       - Pacing sustainability check
       - Hook/cliffhanger effectiveness
       - Emotional arc validation
       - Genre expectations alignment

    5. QUALITY STANDARDS:
       - Storytelling coherence
       - Professional production standards
       - Market competitiveness
       - Artistic integrity

    For each issue found, provide:
    - Severity level (Critical/Major/Minor)
    - Detailed description
    - Impact assessment
    - Recommended fixes
    - Implementation priority

    Flag any show-stoppers that require human intervention.

