# Station 5: Season Architecture Configuration

model: "z-ai/glm-4.5"
temperature: 0.7
max_tokens: 3000

prompts:
  main: |
    You are the Season Architect for audio drama using the 48-style SCREENPLAY STYLE LIBRARY.

    PROJECT CONTEXT: {project_context}

    Return ONLY valid JSON:

    ```json
    {{
      "style_recommendations": [
        {{
          "style_name": "Style from 48-style library",
          "fit_reasoning": "Why this fits the project",
          "audio_adaptation": "Audio strategy",
          "episode_implications": "Episode structure impact",
          "demo_script": "60-second demo",
          "confidence_score": 0.85
        }}
      ],
      "macro_structure": {{
        "act_1_episodes": [1, 2, 3],
        "act_2_episodes": [4, 5, 6, 7],
        "act_3_episodes": [8, 9, 10],
        "structure_explanation": "How acts map to episodes"
      }},
      "episode_grid": [
        {{
          "episode_number": 1,
          "primary_function": "Setup",
          "energy_level": 7,
          "subplot_focus": "Character intro",
          "cliffhanger_type": "Reveal",
          "act_equivalent": "Act 1",
          "special_notes": "Notes"
        }}
      ],
      "rhythm_mapping": {{
        "tension_peaks": [3, 7, 10],
        "breathing_room": [2, 5],
        "format_breaks": ["Episode 6: Special format"],
        "revelation_cascade_points": ["Episode 4: Major reveal"],
        "energy_curve": [5, 6, 8, 7, 6, 7, 9, 8, 9, 10],
        "pacing_strategy": "Build and release pattern",
        "narrator_rhythm_integration": "Narrator usage strategy"
      }}
    }}
    ```

    CRITICAL: Return ONLY valid JSON. Generate 3 style recommendations and episode grid for all episodes.



dependencies:
  - station: 2
    name: "Project DNA Builder"
  - station: 3
    name: "Age Genre Optimizer"
  - station: 4
    name: "Reference Miner"
# Enable/disable this station in the pipeline
enabled: true

