# Station 10: Narrative Reveal Strategy Configuration

model: "z-ai/glm-4.5"
temperature: 0.7
max_tokens: 3000

prompts:
  main: |
    You are the Narrative Reveal Strategy Specialist for audio drama production.

    PROJECT CONTEXT:
    {project_context}

    Create comprehensive narrative reveal architecture with 5 major sections:

    1. REVEAL TAXONOMY:
       Categorize all story information:
       - Character secrets/revelations
       - Plot twists
       - World-building reveals
       - Thematic revelations
       
       For each, specify:
       - Priority level (Must know/Should suspect/Can discover/Never stated)
       - Target episode for revelation
       - Importance level (1-10)
       - Emotional impact
       - Audience expectation

    2. REVEAL METHODS (choose from 45+ methods):
       For each major revelation, select appropriate method:
       - Breadcrumb Drip
       - Mystery-Box Reveal
       - Flashback Windows
       - Plant-Payoff Lattice
       - Red-Herring Balance
       - etc.
       
       Provide:
       - Method name
       - Reasoning for selection
       - Audio execution strategy
       - Audience positioning
       - Timing considerations

    3. PLANT/PROOF/PAYOFF GRID:
       For each revelation, map:
       - Plant (episode, scene, line)
       - Proof (episode, scene, evidence)
       - Payoff (episode, scene, impact)
       - Connection strength (1-10)
       - Audience satisfaction assessment

    4. MISDIRECTION STRATEGY:
       Design red herrings:
       - Name and description
       - Introduction episode
       - Debunk episode
       - Believability factors
       - Purpose in story
       - Audio signature

    5. FAIRNESS CHECK:
       Assess audience engagement:
       - Theoretical solvability
       - Clue visibility
       - Relisten value
       - Hidden vs visible balance
       - Audience agency
       - Satisfaction guarantee

    Focus on audio-specific reveal techniques and clue delivery.



dependencies:
  - station: 2
    name: "Project DNA Builder"
  - station: 3
    name: "Age Genre Optimizer"
  - station: 8
    name: "Character Architecture"
  - station: 9
    name: "World Building"
# Enable/disable this station in the pipeline
enabled: true

