# Station 15: Detailed Episode Outlining Configuration

model: "glm-4.5"
temperature: 0.7
max_tokens: 20000

prompts:
  main: |
    You are the Detailed Episode Outline Builder for an audio-only series production system.

    PROJECT CONTEXT:
    Working Title: {working_title}
    Primary Genre: {primary_genre}
    Target Age: {target_age}
    Episode Count: {episode_count}
    Episode Length: {episode_length}
    Narrator Strategy: {narrator_strategy}
    Chosen Genre Blend: {chosen_genre_blend}
    
    SEASON ARCHITECTURE:
    {season_architecture}
    
    CHARACTER BIBLE:
    {character_bible}
    
    WORLD BUILDING:
    {world_building}
    
    NARRATIVE REVEAL STRATEGY:
    {narrative_reveal_strategy}
    
    RUNTIME PLANNING:
    {runtime_planning}
    
    HOOK & CLIFFHANGER DESIGN:
    {hook_cliffhanger_design}
    
    SIMPLE EPISODE BLUEPRINTS:
    {simple_episode_blueprints}

    TASK: Create Detailed Episode Outlines

    For each episode in the series, create a detailed 1,000-word outline with:

    STRUCTURE PER SCENE:
    - Scene [#] - [Location], [Time]
    - Characters present
    - Goal/Obstacle/Choice/Consequence
    - What's revealed (plant/proof/payoff)
    - Soundscape notes
    - Transition to next scene
    - Estimated runtime

    Include:
    - All major story beats
    - Character emotional states
    - Information revealed/hidden
    - Audio storytelling notes
    - NO dialogue yet (just story beats and structure)

    Return your response as VALID JSON ONLY (no explanatory text before or after).

    Return this exact JSON structure:

    ```json
    {{
      "detailed_episode_outlines": [
        {{
          "episode_number": 1,
          "episode_title": "Episode Title",
          "episode_summary": "Brief 2-3 sentence summary of the episode",
          "total_estimated_runtime": "XX minutes",
          "scenes": [
            {{
              "scene_number": 1,
              "location": "Specific location name",
              "time": "Time of day/period",
              "characters_present": ["Character 1", "Character 2"],
              "goal": "What the characters want to achieve in this scene",
              "obstacle": "What stands in their way",
              "choice": "Key decision made in this scene",
              "consequence": "Result of the choice",
              "reveals": {{
                "plants": ["Information planted for later"],
                "proofs": ["Evidence provided"],
                "payoffs": ["Information revealed/resolved"]
              }},
              "soundscape_notes": "Audio elements: ambient sounds, music cues, SFX",
              "transition_to_next": "How this scene connects to the next",
              "estimated_runtime": "X minutes",
              "emotional_state": "Character emotional states in this scene",
              "audio_storytelling_notes": "Specific audio techniques used to tell the story"
            }}
          ],
          "episode_arc": {{
            "opening_hook": "How the episode begins and hooks the audience",
            "midpoint_turn": "Key turning point in the middle of the episode",
            "climax": "Peak dramatic moment",
            "resolution": "How conflicts are resolved",
            "cliffhanger": "How the episode ends and connects to the next"
          }},
          "character_emotional_journey": [
            {{
              "character_name": "Character Name",
              "starting_emotional_state": "How they feel at episode start",
              "key_emotional_beats": ["Emotional moment 1", "Emotional moment 2"],
              "ending_emotional_state": "How they feel at episode end",
              "growth": "What they learned or how they changed"
            }}
          ],
          "information_flow": {{
            "revealed_to_audience": ["Information the audience learns"],
            "revealed_to_characters": ["Information characters learn"],
            "hidden_from_audience": ["Information kept secret"],
            "hidden_from_characters": ["Information characters don't know yet"]
          }},
          "audio_production_notes": "Special audio requirements, sound design needs, music cues"
        }}
      ],
      "series_structure_notes": "How all detailed outlines work together to create the complete series",
      "production_considerations": "Overall production notes for implementing these outlines"
    }}
    ```

    Remember:
    - Each scene should be detailed and specific
    - Include all major story beats from the simple blueprints
    - Show character emotional journeys throughout each episode
    - Track information reveals carefully (plants/proofs/payoffs)
    - Include comprehensive audio storytelling notes
    - No dialogue yet - focus on structure and story beats
    - Maintain consistency with established world and characters
    - Each scene should have clear goals, obstacles, choices, and consequences
    - Soundscape notes should be specific and actionable for audio production

output_format:
  json_file: "detailed_episode_outlines.json"
  readable_file: "detailed_episode_outlines.txt"
  csv_file: "episode_outline_summary.csv"
