# Station 8: Character Architecture Configuration

model: "z-ai/glm-4.5"
temperature: 0.7
max_tokens: 3000

prompts:
  protagonist_analysis: |
    You are the Character Architect specializing in protagonist design for audio drama.

    PROJECT CONTEXT:
    {project_context}

    Create detailed protagonist profiles (Tier 1 characters).

    For each protagonist, provide:

    1. CORE IDENTITY:
       - Name and age
       - Physical description (voice-relevant traits)
       - Background summary
       - Current situation

    2. PSYCHOLOGICAL PROFILE:
       - Core personality traits
       - Fears and desires
       - Internal conflicts
       - Emotional patterns

    3. ARC STRUCTURE:
       - Starting point (Episode 1)
       - Major transformation moments
       - Mid-point crisis
       - Final state/growth

    4. AUDIO IDENTITY:
       - Voice description
       - Speech patterns
       - Accent/dialect notes
       - Emotional range expression
       - Signature phrases

    5. RELATIONSHIPS:
       - Key relationship dynamics
       - Character chemistry notes
       - Conflict sources

  supporting_characters: |
    Design supporting character profiles (Tier 2) for audio drama.

    PROJECT CONTEXT:
    {project_context}

    PROTAGONIST PROFILES:
    {protagonist_profiles}

    For each supporting character:
    - Name, role, and function in story
    - Relationship to protagonists
    - Character arc (if applicable)
    - Audio voice identity
    - Appearance schedule
    - Key scenes/moments

  recurring_characters: |
    Design recurring characters (Tier 3) for audio drama.

    PROJECT CONTEXT:
    {project_context}

    Create profiles for recurring minor characters.

    Focus on:
    - Distinctive audio identity
    - Memorable voice traits
    - Clear function in story
    - Easy audience identification

  relationship_dynamics: |
    Map relationship dynamics between all characters.

    CHARACTERS:
    {all_characters}

    Create relationship matrix showing:
    - Connection type
    - Dynamic evolution
    - Conflict sources
    - Chemistry notes
    - Key interaction moments

  casting_guidance: |
    Provide casting guidance for voice actors.

    ALL CHARACTER PROFILES:
    {all_characters}

    For each character, specify:
    - Voice type needed
    - Age range
    - Accent requirements
    - Emotional range needed
    - Special vocal skills
    - Chemistry considerations



dependencies:
  - station: 2
    name: "Project DNA Builder"
  - station: 3
    name: "Age Genre Optimizer"
  - station: 4
    name: "Reference Miner"
  - station: 5
    name: "Season Architecture"
# Enable/disable this station in the pipeline
enabled: true

