# Station 41: Cross-Episode Dependency Check Configuration

model: "glm-4.5"
temperature: 0.3
max_tokens: 16000

prompts:
  knowledge_dependencies: |
    You are a Knowledge Dependency Analyst for audio series production.
    
    Analyze information flow across all episodes to identify knowledge dependencies.
    
    SESSION CONTEXT:
    Session ID: {session_id}
    Total Episodes: {total_episodes}
    
    EPISODE SUMMARIES:
    {episode_summaries}
    
    NARRATIVE REVEAL STRATEGY:
    {reveal_strategy}
    
    TASK 1: KNOWLEDGE DEPENDENCIES ANALYSIS
    
    Analyze information dependencies across episodes:
    
    1. **FORWARD DEPENDENCIES** (What Episode X needs from earlier episodes):
       - Information that Episode X assumes is known
       - Plot points that Episode X references
       - Character knowledge that Episode X relies on
       - World rules/events that Episode X builds upon
    
    2. **BACKWARD DEPENDENCIES** (What Episode X sets up for later episodes):
       - Information that Episode X introduces
       - Plot points that Episode X establishes
       - Character knowledge that Episode X creates
       - World events that Episode X triggers
    
    3. **CRITICAL PATHS** (Information chains that cannot break):
       - Dependencies that form chains across multiple episodes
       - Information that MUST be introduced before use
       - Knowledge that cannot be reordered
    
    Return ONLY valid JSON:
    
    ```json
    {{
      "knowledge_dependencies": {{
        "dependencies": [
          {{
            "from_episode": 1,
            "to_episode": 3,
            "category": "knowledge",
            "dependency_type": "forward|backward|critical_path",
            "information_element": "specific information or plot point",
            "description": "what information flows from episode X to Y",
            "criticality": "CRITICAL|HIGH|MEDIUM|LOW",
            "cannot_reorder": true/false,
            "audio_callback_required": true/false
          }}
        ],
        "forward_dependencies_summary": {{
          "total_forward_deps": 0,
          "by_episode": {{
            "episode_X": ["list of dependencies"]
          }}
        }},
        "backward_dependencies_summary": {{
          "total_backward_deps": 0,
          "by_episode": {{
            "episode_X": ["list of setups"]
          }}
        }},
        "critical_paths": [
          {{
            "path": [1, 3, 5, 7],
            "information_flow": "description of the critical information chain",
            "cannot_break": true
          }}
        ]
      }}
    }}
    ```
    
    CRITICAL: Identify ALL information dependencies. Be thorough - missing a dependency can break continuity.
    
  character_dependencies: |
    You are a Character Dependency Analyst for audio series production.
    
    Analyze character dependencies across all episodes.
    
    SESSION CONTEXT:
    Session ID: {session_id}
    Total Episodes: {total_episodes}
    
    CHARACTER APPEARANCES:
    {character_appearances}
    
    CHARACTER BIBLE:
    {character_bible}
    
    TASK 2: CHARACTER DEPENDENCIES ANALYSIS
    
    Analyze character dependencies across episodes:
    
    1. **RELATIONSHIP DEPENDENCIES**:
       - Relationships that must exist before certain episodes
       - Relationship developments that depend on previous episodes
       - Character dynamics that Episode X assumes are established
    
    2. **CHARACTER KNOWLEDGE DEPENDENCIES**:
       - What each character knows at each episode
       - Knowledge that Episode X assumes characters have
       - Knowledge that Episode X establishes for characters
    
    3. **CHARACTER PRESENCE DEPENDENCIES**:
       - Who must be present where when
       - Travel time requirements between episodes
       - Character availability for voice recording
    
    Return ONLY valid JSON:
    
    ```json
    {{
      "character_dependencies": {{
        "dependencies": [
          {{
            "from_episode": 1,
            "to_episode": 3,
            "category": "character",
            "dependency_type": "relationship|knowledge|presence",
            "characters_involved": ["character1", "character2"],
            "description": "what character dependency exists from episode X to Y",
            "criticality": "CRITICAL|HIGH|MEDIUM|LOW",
            "cannot_reorder": true/false
          }}
        ],
        "relationship_dependencies": {{
          "relationships_required": [
            {{
              "relationship": "character1-character2",
              "must_exist_by_episode": 3,
              "established_in_episode": 1,
              "cannot_reorder": true/false
            }}
          ]
        }},
        "character_knowledge_map": {{
          "character_name": {{
            "episode_X": ["what they know"],
            "episode_Y": ["what they know"],
            "knowledge_flow": ["what knowledge they gained between episodes"]
          }}
        }},
        "presence_requirements": [
          {{
            "episode": 3,
            "required_characters": ["character1", "character2"],
            "travel_time_from_previous": "time requirement",
            "voice_recording_needs": "special requirements"
          }}
        ]
      }}
    }}
    ```
    
    CRITICAL: Track character knowledge, relationships, and presence requirements carefully.
    
  world_dependencies: |
    You are a World Dependency Analyst for audio series production.
    
    Analyze world dependencies across all episodes.
    
    SESSION CONTEXT:
    Session ID: {session_id}
    Total Episodes: {total_episodes}
    
    WORLD DATA (Locations per episode):
    {world_data}
    
    WORLD BIBLE:
    {world_bible}
    
    TASK 3: WORLD DEPENDENCIES ANALYSIS
    
    Analyze world dependencies across episodes:
    
    1. **LOCATION DEPENDENCIES**:
       - When locations become available
       - Travel requirements between locations
       - Acoustic establishment needs
    
    2. **TIME DEPENDENCIES**:
       - Day/night requirements
       - Season requirements
       - Timeline constraints between episodes
    
    3. **TECHNOLOGY/MAGIC DEPENDENCIES**:
       - When technology/magic becomes available
       - How it's discovered/learned
       - Audio introduction requirements
    
    Return ONLY valid JSON:
    
    ```json
    {{
      "world_dependencies": {{
        "dependencies": [
          {{
            "from_episode": 1,
            "to_episode": 3,
            "category": "world",
            "dependency_type": "location|time|technology|magic",
            "world_element": "specific location, time, or technology",
            "description": "what world dependency exists from episode X to Y",
            "criticality": "CRITICAL|HIGH|MEDIUM|LOW",
            "cannot_reorder": true/false
          }}
        ],
        "location_availability": {{
          "location_name": {{
            "first_available_in_episode": 1,
            "requires_previous_setup": true/false,
            "travel_time_requirements": "description",
            "acoustic_establishment": "how location sounds are introduced"
          }}
        }},
        "time_dependencies": [
          {{
            "episode": 3,
            "time_requirements": "day/night/season",
            "time_passed_since_previous": "time description",
            "timeline_constraints": "any constraints"
          }}
        ],
        "technology_magic_dependencies": [
          {{
            "element": "technology/magic name",
            "introduced_in_episode": 1,
            "available_from_episode": 2,
            "audio_signature": "how it sounds",
            "cannot_reorder": true/false
          }}
        ]
      }}
    }}
    ```
    
    CRITICAL: Track location access, time progression, and technology/magic availability carefully.
    
  audio_dependencies: |
    You are an Audio Dependency Analyst for audio series production.
    
    Analyze audio dependencies across all episodes.
    
    SESSION CONTEXT:
    Session ID: {session_id}
    Total Episodes: {total_episodes}
    
    AUDIO ELEMENTS PER EPISODE:
    {audio_elements}
    
    STYLE GUIDE:
    {style_guide}
    
    TASK 4: AUDIO DEPENDENCIES ANALYSIS
    
    Analyze audio dependencies across episodes:
    
    1. **MOTIF DEPENDENCIES**:
       - When motifs are introduced
       - When they must recur
       - How they transform across episodes
    
    2. **MUSIC DEPENDENCIES**:
       - Themes established in earlier episodes
       - When music themes must return
       - Emotional associations created
    
    3. **SIGNATURE SOUNDS**:
       - Character sounds that must be consistent
       - Location sounds that must match
       - Object sounds that must recur
    
    Return ONLY valid JSON:
    
    ```json
    {{
      "audio_dependencies": {{
        "dependencies": [
          {{
            "from_episode": 1,
            "to_episode": 3,
            "category": "audio",
            "dependency_type": "motif|music|signature_sound",
            "audio_element": "specific sound, motif, or theme",
            "description": "what audio dependency exists from episode X to Y",
            "criticality": "CRITICAL|HIGH|MEDIUM|LOW",
            "cannot_reorder": true/false,
            "audio_callback_required": true/false,
            "callback_type": "motif_recurrence|theme_return|sound_signature",
            "implementation_notes": "how to implement the audio callback"
          }}
        ],
        "motif_dependencies": [
          {{
            "motif": "motif name or description",
            "introduced_in_episode": 1,
            "must_recur_in_episodes": [3, 5, 7],
            "transformation": "how it changes",
            "cannot_reorder": true/false
          }}
        ],
        "music_dependencies": [
          {{
            "theme": "music theme name",
            "established_in_episode": 1,
            "returns_in_episodes": [3, 5],
            "emotional_association": "what emotion it represents",
            "cannot_reorder": true/false
          }}
        ],
        "signature_sounds": [
          {{
            "sound_type": "character|location|object",
            "element": "specific sound identifier",
            "first_heard_in_episode": 1,
            "must_be_consistent_in_episodes": [2, 3, 4],
            "audio_signature": "description of the sound",
            "cannot_reorder": true/false
          }}
        ]
      }}
    }}
    ```
    
    CRITICAL: Track all audio callbacks and recurring elements. Missing an audio callback breaks continuity.

dependencies:
  - station: 27
    name: "Master Script Assembly"
  - station: 2
    name: "Project DNA Builder"
  - station: 5
    name: "Season Architecture"
  - station: 7
    name: "Character Architecture"
  - station: 8
    name: "World Builder"
  - station: 10
    name: "Narrative Reveal Strategy"

# Enable/disable this station in the pipeline
enabled: true

# Configuration values
input_path: "output/station_27"
output_path: "output/station_41"

# Output enhancements
output_enhancements:
  encoding: "utf-8"
  include_statistics: true
  max_dependencies_per_category: 100

