# Station 9: World Building Configuration

model: "qwen-72b"
temperature: 0.7
max_tokens: 3000

prompts:
  geography: |
    You are the World Building Specialist focusing on geography for audio drama.

    PROJECT CONTEXT:
    {project_context}

    Create detailed geography with audio-specific considerations:

    1. PRIMARY LOCATIONS (5-7 key places):
       - Name and type
       - Audio signature (how it sounds)
       - Ambient soundscape
       - Acoustic properties
       - Emotional association
       - Story function

    2. SECONDARY LOCATIONS (8-12 places):
       - Brief descriptions
       - Audio identifiers
       - Appearance frequency

    3. LOCATION RELATIONSHIPS:
       - Distance/travel time
       - Connection methods
       - Transition sounds

    Focus on how each location SOUNDS different for audio clarity.

  social_structures: |
    Design social structures and cultural elements for audio drama.

    PROJECT CONTEXT:
    {project_context}

    GEOGRAPHY:
    {geography}

    Create:
    - Social hierarchies
    - Cultural norms
    - Power structures
    - Institutions
    - Social dynamics
    - Cultural markers audible in dialogue

  technology_magic: |
    Define technology/magic systems with audio implications.

    PROJECT CONTEXT:
    {project_context}

    Specify:
    - Technology level
    - Key technologies
    - Audio signatures for tech/magic
    - How systems affect daily life
    - Limitations and rules
    - Sound design implications

  history_events: |
    Create relevant history and significant events.

    PROJECT CONTEXT:
    {project_context}

    Provide:
    - Timeline of key events
    - How history affects present
    - Cultural memory
    - Historical references in dialogue
    - Background for character motivations

  sensory_experience: |
    Design complete sensory experience for audio drama.

    PROJECT CONTEXT:
    {project_context}

    ALL WORLD ELEMENTS:
    {world_elements}

    Create audio-specific sensory profile:
    - Signature sounds for each location
    - Ambient soundscapes
    - Character-associated sounds
    - Emotional audio cues
    - Scene transition sounds
    - World-specific audio vocabulary

  world_glossary: |
    Create glossary of world-specific terms for audio drama.

    WORLD ELEMENTS:
    {world_elements}

    For each term provide:
    - Term name
    - Pronunciation guide
    - Definition
    - Context of use
    - First introduction episode
    - Frequency of use

