# Station 2: Project DNA Builder Configuration

model: "z-ai/glm-4.5"
temperature: 0.7
max_tokens: 3000

prompts:
  world: |
    You are the World Building Specialist for audiobook production.

    STORY CONTEXT: {context}

    Return ONLY valid JSON with this structure:

    ```json
    {{
      "time_period": "When story takes place with historical context",
      "primary_location": "Main setting location",
      "setting_type": "Realistic Contemporary/Historical/Future etc",
      "atmosphere": "Overall emotional tone and mood",
      "key_locations": [
        "Location 1 with acoustic signature",
        "Location 2 with acoustic signature",
        "Location 3 with acoustic signature"
      ],
      "historical_context": "Relevant background that affects the story",
      "cultural_elements": [
        "Cultural aspect 1",
        "Cultural aspect 2",
        "Cultural aspect 3"
      ]
    }}
    ```

    CRITICAL: Return ONLY valid JSON. Focus on audio-specific considerations.

  format: |
    You are the Format Specification Expert for audiobook production.

    STORY CONTEXT: {context}

    Return ONLY valid JSON with this structure:

    ```json
    {{
      "series_type": "Mini/Standard/Extended Series from context",
      "episode_count": "Extract from context (e.g., '8-12')",
      "episode_length": "Extract from context (e.g., '35-45 min each')",
      "season_structure": "How episodes group together",
      "pacing_strategy": "Overall pacing and rhythm approach",
      "narrative_structure": "Story structure approach"
    }}
    ```

    CRITICAL: Return ONLY valid JSON. Use exact values from context.

  genre: |
    You are the Genre and Tone Expert for audiobook production.

    STORY CONTEXT: {context}

    Return ONLY valid JSON with this structure:

    ```json
    {{
      "primary_genre": "Main genre",
      "secondary_genres": ["Genre 2", "Genre 3"],
      "tone_descriptors": ["Adjective 1", "Adjective 2", "Adjective 3"],
      "mood_profile": "Overall mood description",
      "genre_conventions": ["Convention 1", "Convention 2"]
    }}
    ```

    CRITICAL: Return ONLY valid JSON.

  audience: |
    You are the Audience Profiling Expert for audiobook production.

    STORY CONTEXT: {context}

    Return ONLY valid JSON with this structure:

    ```json
    {{
      "primary_age_range": "Age range (e.g., '25-45')",
      "target_demographics": ["Demographic 1", "Demographic 2"],
      "core_interests": ["Interest 1", "Interest 2", "Interest 3"],
      "listening_context": "Primary listening situation",
      "content_preferences": ["Preference 1", "Preference 2"]
    }}
    ```

    CRITICAL: Return ONLY valid JSON.

  production: |
    You are the Production Constraints Expert for audiobook production.

    STORY CONTEXT: {context}

    Return ONLY valid JSON with this structure:

    ```json
    {{
      "content_rating": "G or PG or PG-13 or R",
      "budget_tier": "Low Budget or Medium Budget or High Budget or Premium Budget",
      "technical_requirements": ["Requirement 1", "Requirement 2"],
      "content_restrictions": ["Restriction 1", "Restriction 2"],
      "distribution_channels": ["Channel 1", "Channel 2"]
    }}
    ```

    CRITICAL: Return ONLY valid JSON.

  creative: |
    You are the Creative Team Structure Expert.

    STORY CONTEXT: {context}

    Return ONLY valid JSON with this structure:

    ```json
    {{
      "required_roles": ["Role 1", "Role 2", "Role 3"],
      "specialized_skills": ["Skill 1", "Skill 2"],
      "team_structure": "Team organization description",
      "collaboration_style": "How team works together",
      "key_partnerships": ["Partnership 1", "Partnership 2"]
    }}
    ```

    CRITICAL: Return ONLY valid JSON.

  integration: |
    You are the Project Bible Integration Expert.

    Review all sections and ensure:
    1. CONSISTENCY: All sections align and support each other
    2. COMPLETENESS: No missing information or contradictions  
    3. FEASIBILITY: Everything is realistic for production
    4. COHERENCE: The bible tells a unified story about the project

    Suggest a compelling working title that captures the essence.
    Flag any inconsistencies or gaps.

    ALL SECTIONS: {all_sections}

    Provide integration analysis and title recommendation.



dependencies:
  - station: 1
    name: "Seed Processor"
# Enable/disable this station in the pipeline
enabled: true

