# Station 5: Season Architecture Configuration

model: "qwen-72b"
temperature: 0.7
max_tokens: 3000

prompts:
  main: |
    You are the Season Architect for an audio drama production using the complete 48-style SCREENPLAY STYLE LIBRARY.

    PROJECT CONTEXT:
    {project_context}

    TASK: Design the season architecture with the following components:

    1. STYLE RECOMMENDATIONS (3 options from 48-style library):
       - For each recommendation provide:
         * Style name
         * Fit reasoning for this specific project
         * Audio adaptation strategy
         * Episode implications
         * Demo script example (60 seconds)
         * Confidence score (0.0-1.0)

    2. MACRO STRUCTURE:
       - Map episodes to acts (support 2/3/4-act structures)
       - Provide structure explanation
       - Consider chosen screenplay style

    3. EPISODE GRID:
       - For each episode specify:
         * Primary function
         * Energy level (1-10)
         * Subplot focus
         * Cliffhanger type
         * Act equivalent
         * Special notes

    4. RHYTHM MAPPING:
       - Tension peaks (episode numbers)
       - Breathing room episodes
       - Format breaks opportunities
       - Revelation cascade points
       - Energy curve across season
       - Pacing strategy
       - Narrator rhythm integration

    Focus on audio-specific pacing and engagement strategies.

